### ISSUE TITLE
Improve error when providing a Connector type instead of an instance in mock.Projection

### ISSUE THREAD

**Issue by muffgaga** [NeuralEnsemble/PyNN#692]
master HEAD in the mock backend throws an error in `…/pyNN/mock/projections.py` line 43.
(We used the test introduced in PR #691.)
```
Traceback (most recent call last):
  File "test/system/test_speed_mock.py", line 201, in test_scaling                                                                                                                   
    self.do_scaling_test(N)                          
  File "test/system/test_speed_mock.py", line 179, in do_scaling_test 
    proj = sim.Projection(        
  File "…/pyNN/mock/projections.py", line 43, in __init__
    connector.connect(self)
TypeError: connect() missing 1 required positional argument: 'projection'
```

when providing a Connector type instead of an instance when creating a `Projection`:

```python
proj = sim.Projection(pre, post, sim.OneToOneConnector, synapse_type=sim.StaticSynapse(weight=1.0))
```

The error itself is probably correct, but the error message could be improved to better explain the user error.
