### ISSUE TITLE
NEST error while compiling

### ISSUE THREAD

**Issue by Tigerji** [NeuralEnsemble/PyNN#812]
UserWarning:Unable to compile NEST extensions. Output was:
  [ 50%] Building CXX object CMakeFiles/pynn_extensions_module.dir/pynn_extensions.cpp.o
  In file included from /usr/include/nest/sort.h:36,
                   from /usr/include/nest/connector_base.h:35,
                   from /usr/include/nest/connector_base_impl.h:23,
                   from /usr/include/nest/connection.h:29,
                   from /home/tiger/.local/lib/python3.12/site-packages/pyNN/nest/extensions/simple_stochastic_synapse.h:11,
                   from /home/tiger/.local/lib/python3.12/site-packages/pyNN/nest/extensions/pynn_extensions.cpp:9:
  /usr/include/nest/iterator_pair.h:26:10: fatal error: boost/iterator/iterator_adaptor.hpp: No such file or directory
     26 | #include <boost/iterator/iterator_adaptor.hpp>
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  make[2]: *** [CMakeFiles/pynn_extensions_module.dir/build.make:79: CMakeFiles/pynn_extensions_module.dir/pynn_extensions.cpp.o] Error 1
  make[1]: *** [CMakeFiles/Makefile2:120: CMakeFiles/pynn_extensions_module.dir/all] Error 2
  make: *** [Makefile:156: all] Error 2
  
This error occured a few times previously since upgraded ubuntu to 24.04, but now it is much more frequent recently. Tried to re-install NEST and update CMAKE, also tried update CMAKE then re-install NEST does not work.

Despite the error message, most of the time the code still runs, occationally the code would stuck and takes a long time to compile. Any suggestion? Or shall I roll back to 22.04?

**Comment by Tigerji** [comment]
Another compiling issue appeared: seems like part of the pynn.nest package uses numpy were compiled with numpy 1.X. Accidentallly upgraded the numpy to 2.0, now pyNN.nest wont load. Need to downgrade numpy to 1.26.4, then this CMake error occur like all the time, even with the simplist program.

**Comment by Tigerji** [comment]
Tried clean system install, with 22.04 and 24.04, same error occured:
After fresh OS install, install pyNN and nest provides error as : no cmake found
After cmake is installed provide error as: no nest found
re-install nest and pyNN (force reinstall): provide error similar with the original post:
[50% ] building CXX object...

Tested this fresh instlaled system with some nest computation code, some code got executed but some code went into infinit loop that does not provide any output...

Since there is no way to uninstall the CMake, will have to reinstall the OS again and hope the code can run without CMake.

**Comment by apdavison** [comment]
Hi. By "22.04 and 24.04" are you referring to Ubuntu? Which version of NEST are you installing, and which version of PyNN?
